name: Manual Events

on: 
  workflow_dispatch:

jobs: 
  run-manual-tasks:
    runs-on: ubuntu-latest
    steps:
    - name: checkout Repository
      uses: actions/checkout@v4

    - name: info
      run: |
        echo "Checkout successful"
