name: Scheduled Events

on: 
  schedule:
  - cron: '*/5 * * * *'

jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
    - name: info
      run: | 
        echo this is a scheduled task running at every 5 minutes
        
